blogmain/blog/urls.py
from django.conf.urls import url 

from .views import index, add_blog, delete_blog, update_blog, view_blog

urlpatterns = [
	url(r'^$', index, name ='index'),
	url(r'^add_blog$', add_blog, name = 'add_blog'),
	url(r'^delete_blog/(?P<blog_id>\d+)$', delete_blog, name = 'delete_blog'),
	url(r'^update_blog/(?P<blog_id>\d+)$', update_blog, name = 'update_blog'),
	url(r'^view_blog/(?P<blog_id>\d+)$', view_blog, name = 'view_blog'),
	]

blogmain/blogmain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	url(r'^', include(('blog.urls', 'blog'), namespace = "blog")), 
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

blogmain/blog/models.py
from django.db import models

class Blog(models.Model):
	Reviews = 1 
	Profiles = 2
	Rant = 3
	Inspirational =4

	Genre = (
		(Reviews, "Reviews"),
		(Profiles, "Profiles"), 
		(Rant, "Rant"), 
		(Inspirational, "Inspirational")
	)

	Title = models.CharField(verbose_name="Blog Title", max_length= 200)
	Author = models.CharField(verbose_name="Author", max_length= 200)
	Genre = models.IntegerField(verbose_name = "Genre", choices= Genre)
	Content = models.CharField(verbose_name="Content", max_length= 2000)

	def __str__(self):
		return "%s" % self.Title
		

	def get_Title(self):
		return	self.Title

	def get_Author(self):
		return	self.Author

	def get_Genre(self):
		return	self.Genre

	def get_Content(self):
		return	self.Content

blogmain/blog/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
	class Meta:
		model = Blog
		fields = "__all__"

blogmain/blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Blog
from django.urls import reverse_lazy
from .forms import BlogForm


def index(request):
	template = 'list.html'
	blogs = Blog.objects.all()
	context = {
		'blogs': blogs,
	}
	return render(request, template, context)

def add_blog(request):
	template = "add_blog.html"

	if request.method == "POST":
		form = BlogForm(request.POST)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('blog:index'))
	else:
		context = {
			'blog_form': BlogForm(),
		}
	return render(request, template, context)

def update_blog(request, blog_id):
	template = "update_blog.html"
	blogs= Blog.objects.get(id=int(blog_id))

	if request.method == "POST":
		form = BlogForm(request.POST, instance = blogs)
		if form.is_valid():
			form.save()

		return HttpResponseRedirect(reverse_lazy('blog:index'))

	else:
		context = {
			'blog_form': BlogForm(instance=blogs),
		}
	return render(request, template, context)

def delete_blog(request, blog_id):
	blogs = Blog.objects.get(id=int(blog_id))
	blogs.delete()
	return HttpResponseRedirect(reverse_lazy('blog:index'))

	return render(request, template, context)

def view_blog(request, blog_id):
	template = "view_blog.html"
	blog = Blog.objects.get(id=int(blog_id))
	context = {
		'blog': blog,
		}
	return render(request, template, context)

blogmain/templates/add_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		<link rel = "stylesheet" href = "/static/style.css">
	</head>
	<body>
		<h1>Blog Site - Add Blog</h1>

		<form role="form" action="" method="POST">
			{% csrf_token %}

			<table class="table table-striped table-bordered">
				<tr>
					<td>Title</td>
					<td>{{ blog_form.Title }}</td>
				</tr>
				<tr>
					<td>Author</td>
					<td>{{ blog_form.Author}}</td>
				</tr>
				<tr>
					<td>Genre</td>
					<td>{{ blog_form.Genre }}</td>

				</tr>
				<tr>
					<td>Content</td>
					<td>{{ blog_form.Content }}</td>
					
				</tr>
			</table>

			<button class="btn btn-success" type="submit">Save</button>

		</form>

	</body>
</html>

blogmain/templates/list.html
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		<link rel = "stylesheet" href = "/static/style.css">
	</head>
	<body>
		<a align = "right" href="{% url 'blog:add_blog' %}" class="btn btn-success">Add Blog</a> <br /><br />
	<h1 align=center> Blog Site</h1>
	<table class="table table-striped table-bordered">
			<thead>
				<tr align=center>
					<th>Title</th>
					<th>Author</th>
					<th>Genre</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for blog in blogs %}
				<tr>
					<td align=center>{{ blog.Title}}</td>
					<td align=center>{{ blog.Author }}</td>
					<td align=center>{{ blog.get_Genre_display }} </td>
					<td align=center>
						<a href="{% url 'blog:view_blog' blog.id %}" class="btn btn-info">View</a>
					</td>
					<td align=center>
						<a href="{% url 'blog:update_blog' blog.id %}" class="btn btn-primary">Update</a>
					</td>
					<td align=center>
						<a href="{% url 'blog:delete_blog' blog.id %}" class="btn btn-danger">Delete</a>
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan=6>No blogs yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

blogmain/templates/login.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <style type="text/css">
            html,
            body {
                height: 100%;
            }

            body {
                padding-top: 40px;
                padding-bottom: 40px;
            }

            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }
        </style>

    </head>

    <body class="text-center">
        <form class="form-signin" method="POST" action="{% url 'auth_login' %}" role="form">
            {% csrf_token %}

            <h1>Blog Site</h1>

            {{ form.username.label }}
            {{ form.username }}

            {{ form.password.label }}
            {{ form.password }}

            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
            <input type="hidden" name="next" value="{% url 'blog:index' %}" />
        </form>
    </body>
</html>

blogmain/templates/password_change.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>Blog Site</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		{{ form.errors }}

		<form method="POST" action="{% url 'auth_password_change' %}">
		    {% csrf_token %}

		    {{ form.old_password.label }}
		    {{ form.old_password }} <br /><br />

		    {{ form.new_password1.label }}
		    {{ form.new_password1 }} <br /><br />
		    
		    {{ form.new_password2.label }}
		    {{ form.new_password2 }} <br /><br />

		    <button type="submit" class="btn btn-success">Change password</button>
		</form>
	</body>
</html>

blogmain/templates/update_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		<link rel = "stylesheet" href = "/static/style.css">
</head>
	</head>
	<body>
		<h1>Blog Site - Update Blog</h1>

		<form role="form" action="" method="POST">
			{% csrf_token %}

			<table class="table table-striped table-bordered">
				<tr>
					<td>Title</td>
					<td>{{ blog_form.Title }}</td>
				</tr>
				<tr>
					<td>Author</td>
					<td>{{ blog_form.Author }}</td>
				</tr>
				<tr>
					<td>Genre</td>
					<td>{{ blog_form.Genre }}</td>
				</tr>
				<tr>
					<td>Content</td>
					<td>{{ blog_form.Content }}</td>
				</tr>
			</table>

			<button class="btn btn-success" type="submit">Save</button>

		</form>

	</body>
</html>

blogmain/templates/view_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		<link rel = "stylesheet" href = "/static/style.css">
</head>
	</head>
	<body>
		<h1>Blog Site - View Blog</h1>

			<table class="table table-striped table-bordered">
				<tr>
					<td>Title</td>
					<td>{{ blog.get_Title }} </td>
				</tr>
				<tr>
					<td>Author</td>
					<td>{{ blog.get_Author }} </td>
				</tr>
				<tr>
					<td>Genre</td>
					<td>{{ blog.get_Genre }} </td>
				</tr>
				<tr>
					<td>Content</td>
					<td>{{ blog.get_Content }} </td>
				</tr>
			</table>
		</form>

	</body>
</html>